config/routes.rb
Rails.application.routes.draw do
  post 'bitlies/index'

  get 'bitlies/counter'
 
  resources :bitlies
 
  root 'bitlies#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bilty.rb
class Bilty < ApplicationRecord
	def self.create_short
		link = (0..3).map { ('a'..'z').to_a[rand(26)] }.join
	end

  def self.short_url
		check = []
		receive = Bilty.all
		new_short = self.create_short
		receive.each do |generate|
			if generate.short_url == new_short
				self.short_url
			end
		end
		new_short
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bitlies_controller.rb
class BitliesController < ApplicationController
  def index
  	@bitlies = Bilty.all
  end

  def new
	end

	def create
		# evaluando abuelita
		p 'Hola'
		p @bitly = params[:long_url]
		p @short_url = Bilty.short_url
		p @new_url = Bilty.create(long_url: @bitly, short_url: @short_url)
		# render 'index'
  end

  def counter
  	p url_finder = params[:format]
	  find = Bilty.find_by(short_url: url_finder)
	  p find
	  find.click_count += 1
	  find.save
	  redirect_to find.long_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bitlies_helper.rb
module BitliesHelper
end

app/views/bitlies/index.html.erb
<h1>Bienvenido a Mi Bitly!</h1>
<p>Este es un una tabla con Urls reducidos</p>

<%= form_tag bitlies_path do %>
  <p>
  	Acorta tu URL: Por favor utiliza http:// o https://<br>
  	<%= label_tag :long_url %><br>
    <%= text_field_tag :long_url %>
  </p>
 
  <p>
    <%= submit_tag "Search" %>
  </p>
<% end %>

<% @bitlies.each do |show| %>
	<ul>
		<li>
			<%= show.id %><p>	</p><%= show.long_url %><p>	</p><%= link_to "#{show.short_url}", bitlies_counter_path(show.short_url) %></a><p>	</p><%= show.click_count %>
		</li>
	</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bitly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>